language: node_js
node_js:
  - "10"
  - "12"
cache: yarn

install: yarn

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn coverage
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: yarn build
      deploy:
        provider: npm
        email: "$EMAIL_ADDRESS"
        api_key: "$AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
